-include .env
export

.PHONY: dev migrate seed test test-e2e db-reset build

dev:
	@echo "TODO: implement in Task 12"

migrate:
	@echo "TODO: implement in Task 12"

seed: migrate

test:
	@echo "TODO: implement in Task 12"

test-e2e:
	@echo "TODO: implement in Task 12"

db-reset:
	@echo "TODO: implement in Task 12"

build:
	@echo "TODO: implement in Task 12"
